// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "restful://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "restful://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "restful://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/applications": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "获取当前用户收到的所有好友/群聊申请，包含申请人昵称、头像等信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "申请"
                ],
                "summary": "获取收到的申请列表",
                "responses": {
                    "200": {
                        "description": "Token 无效",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "向目标用户发送好友申请(contact_type=0)或向群聊发送加群申请(contact_type=1)，可附加留言",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "申请"
                ],
                "summary": "发起好友/群聊申请",
                "parameters": [
                    {
                        "description": "申请参数",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.SubmitApplicationReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "不能添加自己 / 已经是好友 / 申请处理中",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/applications/{uuid}": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "对收到的申请进行处理：1=同意（自动建立双向好友关系）、2=拒绝、3=拉黑",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "申请"
                ],
                "summary": "处理申请",
                "parameters": [
                    {
                        "type": "string",
                        "description": "申请记录 UUID",
                        "name": "uuid",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "处理操作: 1=同意, 2=拒绝, 3=拉黑",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.HandleApplicationReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "申请不存在 / 权限不足 / 已处理过",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/auth/login": {
            "post": {
                "description": "通过手机号和密码登录，验证成功后下发 JWT Token 及用户基本信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "鉴权"
                ],
                "summary": "用户登录",
                "parameters": [
                    {
                        "description": "登录参数",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.LoginReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "账号或密码错误 / 账号被禁用",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/auth/logout": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "登出当前账号，更新最后离线时间（后续可扩展 Token 黑名单机制）",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "鉴权"
                ],
                "summary": "用户登出",
                "responses": {
                    "200": {
                        "description": "Token 无效",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/auth/register": {
            "post": {
                "description": "通过手机号、密码和昵称注册新账号",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "鉴权"
                ],
                "summary": "用户注册",
                "parameters": [
                    {
                        "description": "注册参数",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.RegisterReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "参数错误 / 手机号已注册",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/contacts": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "获取当前用户的所有联系人（好友），包含昵称、头像、状态等信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "联系人"
                ],
                "summary": "获取通讯录列表",
                "responses": {
                    "200": {
                        "description": "Token 无效",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/contacts/{uuid}": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "删除与目标用户的好友关系（双向更新状态：主动方=3，被动方=4）",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "联系人"
                ],
                "summary": "删除好友",
                "parameters": [
                    {
                        "type": "string",
                        "description": "目标用户 UUID",
                        "name": "uuid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "好友关系不存在 / 不能操作自己",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/contacts/{uuid}/block": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "拉黑目标用户（双向更新状态：主动方=1，被动方=2）",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "联系人"
                ],
                "summary": "拉黑好友",
                "parameters": [
                    {
                        "type": "string",
                        "description": "目标用户 UUID",
                        "name": "uuid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "好友关系不存在 / 不能操作自己",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "解除对目标用户的拉黑（双向恢复状态为 0=正常）",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "联系人"
                ],
                "summary": "解除拉黑",
                "parameters": [
                    {
                        "type": "string",
                        "description": "目标用户 UUID",
                        "name": "uuid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "好友关系不存在",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/groups": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "创建一个新的群聊，当前用户自动成为群主；可选择在创建时邀请初始成员",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "群组"
                ],
                "summary": "创建群聊",
                "parameters": [
                    {
                        "description": "群组信息",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.CreateGroupReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "参数错误",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/groups/joined": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "获取当前用户已加入的所有群聊，包含群名、成员数、群主等信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "群组"
                ],
                "summary": "获取我加入的群列表",
                "responses": {
                    "200": {
                        "description": "Token 无效",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/groups/{uuid}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "根据群 UUID 获取群名称、公告、头像、成员数、群主、加群模式等信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "群组"
                ],
                "summary": "获取群详情",
                "parameters": [
                    {
                        "type": "string",
                        "description": "群 UUID",
                        "name": "uuid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "群不存在",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "群主修改群名称、公告、头像、加群模式等（仅传入需修改的字段）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "群组"
                ],
                "summary": "修改群资料",
                "parameters": [
                    {
                        "type": "string",
                        "description": "群 UUID",
                        "name": "uuid",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "需要更新的字段",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.UpdateGroupReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "权限不足 / 群不存在",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "群主解散群聊（仅群主有权限），解散后群内所有会话失效",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "群组"
                ],
                "summary": "解散群聊",
                "parameters": [
                    {
                        "type": "string",
                        "description": "群 UUID",
                        "name": "uuid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "权限不足 / 群不存在",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/groups/{uuid}/members": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "获取指定群聊的所有成员，包含昵称、头像、签名等信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "群组"
                ],
                "summary": "获取群成员列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "群 UUID",
                        "name": "uuid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "群不存在",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "邀请一个或多个用户加入指定群聊",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "群组"
                ],
                "summary": "邀请成员入群",
                "parameters": [
                    {
                        "type": "string",
                        "description": "群 UUID",
                        "name": "uuid",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "被邀请的用户 UUID 列表",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.InviteMemberReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "参数错误 / 群不存在",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/groups/{uuid}/members/me": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "当前用户主动退出指定群聊（群主不能退出，需先转让或解散）",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "群组"
                ],
                "summary": "退出群聊",
                "parameters": [
                    {
                        "type": "string",
                        "description": "群 UUID",
                        "name": "uuid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "不在群中 / 群主不能退出",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/groups/{uuid}/members/{user_id}": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "群主/管理员将指定用户从群聊中移除（不能踢自己）",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "群组"
                ],
                "summary": "踢出群成员",
                "parameters": [
                    {
                        "type": "string",
                        "description": "群 UUID",
                        "name": "uuid",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "被踢用户 UUID",
                        "name": "user_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "权限不足 / 不能踢自己",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/messages": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "分页获取指定会话的历史消息，按发送时间倒序返回",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "消息"
                ],
                "summary": "获取消息列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "会话 UUID",
                        "name": "session_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "minimum": 1,
                        "type": "integer",
                        "description": "页码 (从1开始)",
                        "name": "page",
                        "in": "query",
                        "required": true
                    },
                    {
                        "maximum": 100,
                        "minimum": 1,
                        "type": "integer",
                        "description": "每页数量",
                        "name": "size",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "参数错误 / Token 无效",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/messages/{uuid}/recall": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "撤回自己发送的消息（将消息状态设为 2=已撤回），超时可能被拒绝",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "消息"
                ],
                "summary": "撤回消息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "消息 UUID",
                        "name": "uuid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "消息不存在 / 超时 / 非本人消息",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/sessions": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "分页获取当前用户的聊天会话列表，包含对方名称、头像、最后消息、未读数等",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "会话"
                ],
                "summary": "获取会话列表",
                "parameters": [
                    {
                        "minimum": 1,
                        "type": "integer",
                        "description": "页码 (从1开始)",
                        "name": "page",
                        "in": "query",
                        "required": true
                    },
                    {
                        "maximum": 100,
                        "minimum": 1,
                        "type": "integer",
                        "description": "每页数量",
                        "name": "size",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "参数错误 / Token 无效",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "与目标用户或群组创建一个新会话（如果已存在则返回已有会话的 UUID）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "会话"
                ],
                "summary": "创建会话",
                "parameters": [
                    {
                        "description": "target_id=对方UUID, session_type: 0=私聊, 1=群聊",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.CreateSessionReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "不能与自己发起会话 / 参数错误",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/sessions/{uuid}": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "从当前用户的会话列表中删除指定会话",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "会话"
                ],
                "summary": "删除会话",
                "parameters": [
                    {
                        "type": "string",
                        "description": "会话 UUID",
                        "name": "uuid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "会话不存在",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/sessions/{uuid}/read": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "将指定会话的未读消息数归零",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "会话"
                ],
                "summary": "标记会话已读",
                "parameters": [
                    {
                        "type": "string",
                        "description": "会话 UUID",
                        "name": "uuid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "会话不存在",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/sessions/{uuid}/top": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "设置指定会话的置顶状态：1=置顶, 0=取消置顶",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "会话"
                ],
                "summary": "置顶/取消置顶会话",
                "parameters": [
                    {
                        "type": "string",
                        "description": "会话 UUID",
                        "name": "uuid",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "is_top: 0=取消置顶, 1=置顶",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.PinSessionReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "参数错误",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/users": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "分页获取用户列表，支持通过昵称或手机号进行模糊搜索",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户"
                ],
                "summary": "搜索用户 / 获取用户列表",
                "parameters": [
                    {
                        "minimum": 1,
                        "type": "integer",
                        "description": "页码 (从1开始)",
                        "name": "page",
                        "in": "query",
                        "required": true
                    },
                    {
                        "maximum": 100,
                        "minimum": 1,
                        "type": "integer",
                        "description": "每页数量",
                        "name": "size",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "搜索关键词 (昵称或手机号)",
                        "name": "keyword",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "参数错误",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/users/me": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "根据 Token 中的用户 UUID 返回完整的个人资料",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户"
                ],
                "summary": "获取我的个人信息",
                "responses": {
                    "200": {
                        "description": "Token 无效 / 用户不存在",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "修改当前用户的昵称、邮箱、头像、性别、个性签名等字段，仅传入需要修改的字段",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户"
                ],
                "summary": "更新我的个人信息",
                "parameters": [
                    {
                        "description": "需要更新的字段",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.UpdateProfileReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "参数错误 / Token 无效",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/users/me/delete-request": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "当前登录用户提交注销申请，校验密码后进入注销冷静期，并使当前登录态失效",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户"
                ],
                "summary": "发起账号注销申请",
                "parameters": [
                    {
                        "description": "注销申请参数",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.RequestAccountDeletionReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "参数错误 / 密码错误 / Token 无效",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "当前登录用户在冷静期内校验密码后取消注销申请，恢复账号正常状态",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户"
                ],
                "summary": "取消账号注销申请",
                "parameters": [
                    {
                        "description": "取消注销参数",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.CancelAccountDeletionReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "参数错误 / 密码错误 / Token 无效",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/users/me/phone/change": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "当前登录用户校验密码和验证码后，将登录手机号迁移到新的手机号",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户"
                ],
                "summary": "更换手机号",
                "parameters": [
                    {
                        "description": "更换手机号参数",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.ChangeTelephoneReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "参数错误 / 密码错误 / 手机号已存在",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/users/{uuid}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "根据用户 UUID 获取其公开资料",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户"
                ],
                "summary": "获取指定用户信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "目标用户 UUID",
                        "name": "uuid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "用户不存在",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "管理员操作：删除指定用户（不能删除自己）",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户管理 (Admin)"
                ],
                "summary": "删除用户",
                "parameters": [
                    {
                        "type": "string",
                        "description": "目标用户 UUID",
                        "name": "uuid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "权限不足 / 不能删除自己",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/users/{uuid}/role": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "管理员操作：设置目标用户为普通用户(0)或管理员(1)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户管理 (Admin)"
                ],
                "summary": "设置用户角色",
                "parameters": [
                    {
                        "type": "string",
                        "description": "目标用户 UUID",
                        "name": "uuid",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "角色值: 0=普通用户, 1=管理员",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.SetUserRoleReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "权限不足 / 参数错误",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/users/{uuid}/status": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "管理员操作：设置目标用户的状态为正常(0)或禁用(1)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户管理 (Admin)"
                ],
                "summary": "启用/禁用用户",
                "parameters": [
                    {
                        "type": "string",
                        "description": "目标用户 UUID",
                        "name": "uuid",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "状态值: 0=正常, 1=禁用",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.SetUserStatusReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "权限不足 / 参数错误",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/ws": {
            "get": {
                "description": "将 HTTP 连接升级为 WebSocket 长连接，用于实时消息推送和收发。",
                "tags": [
                    "WebSocket"
                ],
                "summary": "WebSocket 连接",
                "parameters": [
                    {
                        "type": "string",
                        "description": "JWT Token",
                        "name": "token",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "101": {
                        "description": "协议升级成功，WebSocket 连接已建立"
                    },
                    "200": {
                        "description": "Token 无效 / Token 缺失",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "response.Response": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {},
                "msg": {
                    "type": "string"
                }
            }
        },
        "types.ApplicationVO": {
            "type": "object",
            "properties": {
                "avatar": {
                    "description": "申请人的头像",
                    "type": "string"
                },
                "contact_id": {
                    "description": "目标ID (用户ID 或 群ID)",
                    "type": "string"
                },
                "contact_type": {
                    "description": "0.用户，1.群聊",
                    "type": "integer"
                },
                "last_apply_at": {
                    "description": "最后申请时间",
                    "type": "string"
                },
                "message": {
                    "description": "留言信息",
                    "type": "string"
                },
                "nickname": {
                    "description": "申请人的昵称 (需要连表查 User)",
                    "type": "string"
                },
                "status": {
                    "description": "0.待处理, 1.已通过, 2.已拒绝, 3.拉黑",
                    "type": "integer"
                },
                "user_id": {
                    "description": "申请人的 UUID",
                    "type": "string"
                },
                "uuid": {
                    "type": "string"
                }
            }
        },
        "types.CancelAccountDeletionReq": {
            "type": "object",
            "required": [
                "password"
            ],
            "properties": {
                "password": {
                    "type": "string",
                    "maxLength": 20,
                    "minLength": 6
                }
            }
        },
        "types.ChangeTelephoneReq": {
            "type": "object",
            "required": [
                "new_telephone",
                "password",
                "verify_code"
            ],
            "properties": {
                "new_telephone": {
                    "type": "string"
                },
                "password": {
                    "type": "string",
                    "maxLength": 20,
                    "minLength": 6
                },
                "verify_code": {
                    "type": "string"
                }
            }
        },
        "types.ContactVO": {
            "type": "object",
            "properties": {
                "avatar": {
                    "type": "string"
                },
                "contact_id": {
                    "type": "string"
                },
                "nickname": {
                    "type": "string"
                },
                "signature": {
                    "type": "string"
                },
                "status": {
                    "description": "0.正常, 1.拉黑 等等",
                    "type": "integer"
                }
            }
        },
        "types.CreateGroupReq": {
            "type": "object",
            "required": [
                "members",
                "name"
            ],
            "properties": {
                "add_mode": {
                    "type": "integer",
                    "enum": [
                        0,
                        1
                    ]
                },
                "avatar": {
                    "type": "string"
                },
                "members": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "name": {
                    "type": "string",
                    "maxLength": 20
                },
                "notice": {
                    "type": "string",
                    "maxLength": 500
                }
            }
        },
        "types.CreateGroupResp": {
            "type": "object",
            "properties": {
                "uuid": {
                    "type": "string"
                }
            }
        },
        "types.CreateSessionReq": {
            "type": "object",
            "required": [
                "target_id"
            ],
            "properties": {
                "session_type": {
                    "type": "integer",
                    "enum": [
                        0,
                        1
                    ]
                },
                "target_id": {
                    "type": "string"
                }
            }
        },
        "types.CreateSessionResp": {
            "type": "object",
            "properties": {
                "uuid": {
                    "type": "string"
                }
            }
        },
        "types.GetApplicationListResp": {
            "type": "object",
            "properties": {
                "list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/types.ApplicationVO"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "types.GetContactListResp": {
            "type": "object",
            "properties": {
                "list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/types.ContactVO"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "types.GetGroupMembersResp": {
            "type": "object",
            "properties": {
                "list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/types.GroupMemberVO"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "types.GetJoinedGroupsResp": {
            "type": "object",
            "properties": {
                "list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/types.GroupVO"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "types.GetMessageListResp": {
            "type": "object",
            "properties": {
                "list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/types.MessageVO"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "types.GetSessionListResp": {
            "type": "object",
            "properties": {
                "list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/types.SessionVO"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "types.GetUserListResp": {
            "type": "object",
            "properties": {
                "list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/types.UserProfileResp"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "types.GroupMemberVO": {
            "type": "object",
            "properties": {
                "avatar": {
                    "type": "string"
                },
                "nickname": {
                    "type": "string"
                },
                "signature": {
                    "type": "string"
                },
                "uuid": {
                    "type": "string"
                }
            }
        },
        "types.GroupVO": {
            "type": "object",
            "properties": {
                "add_mode": {
                    "type": "integer"
                },
                "avatar": {
                    "type": "string"
                },
                "member_cnt": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "notice": {
                    "type": "string"
                },
                "owner_id": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                },
                "uuid": {
                    "type": "string"
                }
            }
        },
        "types.HandleApplicationReq": {
            "type": "object",
            "required": [
                "status"
            ],
            "properties": {
                "status": {
                    "description": "1:同意 2:拒绝 3:拉黑",
                    "type": "integer",
                    "enum": [
                        1,
                        2,
                        3
                    ]
                }
            }
        },
        "types.InviteMemberReq": {
            "type": "object",
            "required": [
                "user_ids"
            ],
            "properties": {
                "user_ids": {
                    "type": "array",
                    "minItems": 1,
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "types.LoginReq": {
            "type": "object",
            "required": [
                "password",
                "telephone"
            ],
            "properties": {
                "password": {
                    "type": "string"
                },
                "telephone": {
                    "type": "string"
                }
            }
        },
        "types.LoginResp": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string"
                },
                "user_info": {
                    "$ref": "#/definitions/types.UserVO"
                }
            }
        },
        "types.MessageVO": {
            "type": "object",
            "properties": {
                "av_data": {
                    "type": "string"
                },
                "content": {
                    "type": "string"
                },
                "file_name": {
                    "type": "string"
                },
                "file_size": {
                    "type": "integer"
                },
                "file_type": {
                    "type": "string"
                },
                "receive_id": {
                    "type": "string"
                },
                "send_at": {
                    "type": "string"
                },
                "send_id": {
                    "type": "string"
                },
                "session_id": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                },
                "type": {
                    "type": "integer"
                },
                "url": {
                    "type": "string"
                },
                "uuid": {
                    "type": "string"
                }
            }
        },
        "types.PinSessionReq": {
            "type": "object",
            "required": [
                "is_top"
            ],
            "properties": {
                "is_top": {
                    "type": "integer",
                    "enum": [
                        0,
                        1
                    ]
                }
            }
        },
        "types.RegisterReq": {
            "type": "object",
            "required": [
                "confirm_password",
                "nickname",
                "password",
                "telephone"
            ],
            "properties": {
                "confirm_password": {
                    "type": "string"
                },
                "nickname": {
                    "type": "string",
                    "maxLength": 20
                },
                "password": {
                    "type": "string",
                    "maxLength": 20,
                    "minLength": 6
                },
                "telephone": {
                    "description": "根据你的表结构，使用 Telephone 作为主账号",
                    "type": "string"
                }
            }
        },
        "types.RequestAccountDeletionReq": {
            "type": "object",
            "required": [
                "password"
            ],
            "properties": {
                "password": {
                    "type": "string",
                    "maxLength": 20,
                    "minLength": 6
                }
            }
        },
        "types.SessionVO": {
            "type": "object",
            "properties": {
                "is_top": {
                    "type": "integer"
                },
                "last_message": {
                    "type": "string"
                },
                "last_message_at": {
                    "type": "string"
                },
                "session_type": {
                    "type": "integer"
                },
                "target_avatar": {
                    "type": "string"
                },
                "target_id": {
                    "type": "string"
                },
                "target_name": {
                    "type": "string"
                },
                "unread_count": {
                    "type": "integer"
                },
                "uuid": {
                    "type": "string"
                }
            }
        },
        "types.SetUserRoleReq": {
            "type": "object",
            "required": [
                "is_admin"
            ],
            "properties": {
                "is_admin": {
                    "type": "integer",
                    "enum": [
                        0,
                        1
                    ]
                }
            }
        },
        "types.SetUserStatusReq": {
            "type": "object",
            "required": [
                "status"
            ],
            "properties": {
                "status": {
                    "description": "0.正常，1.禁用 (pointer to avoid default zero value)",
                    "type": "integer",
                    "enum": [
                        0,
                        1
                    ]
                }
            }
        },
        "types.SubmitApplicationReq": {
            "type": "object",
            "required": [
                "contact_id"
            ],
            "properties": {
                "contact_id": {
                    "type": "string"
                },
                "contact_type": {
                    "type": "integer",
                    "enum": [
                        0,
                        1
                    ]
                },
                "message": {
                    "type": "string",
                    "maxLength": 100
                }
            }
        },
        "types.UpdateGroupReq": {
            "type": "object",
            "properties": {
                "add_mode": {
                    "type": "integer",
                    "enum": [
                        0,
                        1
                    ]
                },
                "avatar": {
                    "type": "string"
                },
                "name": {
                    "type": "string",
                    "maxLength": 20
                },
                "notice": {
                    "type": "string",
                    "maxLength": 500
                }
            }
        },
        "types.UpdateProfileReq": {
            "type": "object",
            "properties": {
                "avatar": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "gender": {
                    "type": "integer",
                    "enum": [
                        0,
                        1
                    ]
                },
                "nickname": {
                    "type": "string",
                    "maxLength": 20
                },
                "signature": {
                    "type": "string",
                    "maxLength": 100
                }
            }
        },
        "types.UserProfileResp": {
            "type": "object",
            "properties": {
                "avatar": {
                    "type": "string"
                },
                "birthday": {
                    "type": "string"
                },
                "delete_after": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "gender": {
                    "type": "integer"
                },
                "nickname": {
                    "type": "string"
                },
                "signature": {
                    "type": "string"
                },
                "telephone": {
                    "type": "string"
                },
                "uuid": {
                    "type": "string"
                }
            }
        },
        "types.UserVO": {
            "type": "object",
            "properties": {
                "avatar": {
                    "type": "string"
                },
                "nickname": {
                    "type": "string"
                },
                "signature": {
                    "type": "string"
                },
                "uuid": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "WChat API",
	Description:      "WChat 即时通讯系统后端 API 文档",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
